#!/bin/bash
# Pull startup configuration for a new machine
__ScriptVersion="0.1"

# constants
BLUE='\033[0;34m'
NC='\033[0m'  # no Color

# default values for option variables
desktop=false

# usage info
usage() {
  cat << EOF
Usage: startup [-v -h] [--desktop]

General options:

  -v, --version  Print version number and exit.
  -h, --help     Display this help and exit.

  -d, --desktop  Include graphical components for a desktop installation
                 (default server).
EOF
}

# print version
version() {
  echo "Startup configurator -- Version $__ScriptVersion"
}

# parse options
optspec=":dhv-:"
while getopts "$optspec" optchar; do
  case "${optchar}" in

    # Short options
    d) desktop=true;;
    h) usage; exit 0;;
    v) version; exit 0;;
    -)
      case "${OPTARG}" in
        # Long options
        desktop) desktop=true;;
        help)    usage; exit 0;;
        version) version; exit 0;;
      esac;;
    *)
      echo "Unknown option -${OPTARG}" >&2
      usage >&2
      exit 1;;
  esac
done
shift $((OPTIND-1))


# generic stuff
printf "${BLUE}[generic] Installing build tools...${NC}"
sudo apt install build-essential

printf "${BLUE}[generic] Installing git...${NC}"
sudo apt install git

printf "${BLUE}[generic] Installing GNU stow...${NC}"
sudo apt install stow

printf "${BLUE}[generic] DONE${NC}"


# dotfiles
printf "${BLUE}[dotfiles] Pulling...${NC}"
cd ~
git clone https://github.com/kofdog/dotfiles
cd dotfiles

printf "${BLUE}[dotfiles] Linking...${NC}"
mv ~/.bashrc ~/.bashrc.old
stow bash git scripts tmux vim

printf "${BLUE}[dotfiles] DONE${NC}"


# tmux
printf "${BLUE}[tmux] Installing dependencies...${NC}"
sudo apt install libevent-dev libncurses5-dev

printf "${BLUE}[tmux] Pulling sources...${NC}"
cd ~/Documents
git clone https://github.com/tmux/tmux.git
cd tmux

printf "${BLUE}[tmux] Checking out v2.6...${NC}"
git fetch --tags
git checkout 2.6

printf "${BLUE}[tmux] Running autogen...${NC}"
sh autogen.sh

printf "${BLUE}[tmux] Configuring...${NC}"
./configure

printf "${BLUE}[tmux] Building...${NC}"
make -j9

printf "${BLUE}[tmux] Installing...${NC}"
sudo make install

printf "${BLUE}[tmux] Cleaning up...${NC}"
make clean

printf "${BLUE}[tmux] Adding terminfo...${NC}"
tic .config/tmux/tmux-256color.terminfo

printf "${BLUE}[tmux] Installing TPM...${NC}"
cd ~
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

printf "${BLUE}[tmux] DONE${NC}"


# vim
printf "${BLUE}[vim] Installing dependencies...${NC}"
sudo apt install libncurses5-dev libgnome2-dev libgnomeui-dev \
	libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
	libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev \
	python3-dev ruby-dev lua5.1 lua5.1-dev libperl-dev git

printf "${BLUE}[vim] Pulling sources...${NC}"
cd ~/Documents
git clone https://github.com/vim/vim.git
cd vim

printf "${BLUE}[vim] Using latest version...${NC}"
printf "${BLUE}[vim] Configuring...${NC}"
./configure --with-features=huge

printf "${BLUE}[vim] Building...${NC}"
make -j9

printf "${BLUE}[vim] Installing...${NC}"
sudo make install

printf "${BLUE}[vim] Cleaning up...${NC}"
make clean
make distclean

printf "${BLUE}[vim] DONE${NC}"


if [ "$desktop" = true ]; then
	# font
	printf "${BLUE}[font] Pulling nerd fonts...${NC}"
	cd ~/Documents
	git clone https://github.com/ryanoasis/nerd-fonts.git
	cd nerd-fonts

	printf "${BLUE}[font] Installing Source Code Pro...${NC}"
	./install.sh SourceCodePro

	printf "${BLUE}[font] DONE${NC}"


	# theme
	printf "${BLUE}[theme] Pulling gruvbox for GNOME terminal...${NC}"
	cd ~/Documents
	git clone https://github.com/metalelf0/gnome-terminal-colors.git
	cd gnome-terminal-colors

	printf "${BLUE}[theme] Running interactive installer...${NC}"
	./install.sh

	printf "${BLUE}[theme] DONE. Please restart terminal and configure font.${NC}"
fi
