#!/bin/bash
# Pull startup configuration for a new machine
__ScriptVersion="0.1"

# constants
DOC_DIR=~/Documents
BLUE='\033[0;34m'
NC='\033[0m'  # no color

# default values for option variables
desktop=false

# print usage info
usage() {
    cat << EOF
Usage: startup [-v -h] [--desktop]

General options:

  -v, --version  Print version number and exit.
  -h, --help     Display this help and exit.

  -d, --desktop  Include graphical components for a desktop installation
                 (default server).
EOF
}

# print version
version() {
    echo "Startup configurator -- Version $__ScriptVersion"
}

# parse options
optspec=":dhv-:"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        # Short options
        d) desktop=true;;
        h) usage; exit 0;;
        v) version; exit 0;;
        -)
            case "${OPTARG}" in
                # Long options
                desktop) desktop=true;;
                help)    usage; exit 0;;
                version) version; exit 0;;
            esac;;
        *)
            echo "Unknown option -${OPTARG}" >&2
            usage >&2
            exit 1;;
    esac
done
shift $((OPTIND-1))

# print progress in a pretty fashion
prettyprint() {
    printf "${BLUE}$1${NC}\n"
}


# generic stuff
prettyprint "[generic] Updating system..."

sudo apt update
sudo apt upgrade
sudo apt autoremove

prettyprint "[generic] Installing build tools..."

sudo apt install automake build-essential pkg-config

prettyprint "[generic] Installing git..."

sudo apt install git

prettyprint "[generic] Installing GNU stow..."

sudo apt install stow

prettyprint "[generic] Adding placeholder directory..."

mkdir -p $DOC_DIR

prettyprint "[generic] DONE"


# dotfiles
prettyprint "[dotfiles] Pulling..."

cd ~
git clone https://github.com/kofdog/dotfiles
cd dotfiles

prettyprint "[dotfiles] Linking..."

mv ~/.bashrc ~/.bashrc.old
stow bash git scripts tmux vim

prettyprint "[dotfiles] DONE"


# tmux
prettyprint "[tmux] Installing dependencies..."

sudo apt install libevent-dev libncurses5-dev

prettyprint "[tmux] Pulling sources..."

cd ~/Documents
git clone https://github.com/tmux/tmux.git
cd tmux

prettyprint "[tmux] Checking out v2.6..."

git fetch --tags
git checkout 2.6

prettyprint "[tmux] Configuring..."

sh autogen.sh
./configure

prettyprint "[tmux] Building..."

make -j9

prettyprint "[tmux] Installing..."

sudo make install

prettyprint "[tmux] Cleaning up..."

make clean

prettyprint "[tmux] Adding terminfo..."

cd ~/dotfiles/tmux
tic .config/tmux/tmux-256color.terminfo

prettyprint "[tmux] Installing TPM..."

cd ~
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

prettyprint "[tmux] DONE"


# vim
prettyprint "[vim] Installing dependencies..."

sudo apt install libncurses5-dev libgnome2-dev libgnomeui-dev \
    libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
    libcairo2-dev libx11-dev libxpm-dev libxt-dev python-dev \
    python3-dev ruby-dev lua5.1 lua5.1-dev libperl-dev git

prettyprint "[vim] Pulling sources..."

cd ~/Documents
git clone https://github.com/vim/vim.git
cd vim

prettyprint "[vim] Using latest version. Configuring..."

./configure --with-features=huge

prettyprint "[vim] Building..."

make -j9

prettyprint "[vim] Installing..."

sudo make install

prettyprint "[vim] Cleaning up..."

make clean
make distclean

prettyprint "[vim] Pulling Vundle..."
mkdir ~/.vim/bundle
cd ~/.vim/bundle
git clone https://github.com/VundleVim/Vundle.vim

prettyprint "[vim] DONE. Be sure to load Vundle plugins."


# graphical stuff
if [ "$desktop" = true ]; then
    # font
    prettyprint "[font] Pulling nerd fonts..."

    cd ~/Documents
    git clone https://github.com/ryanoasis/nerd-fonts.git
    cd nerd-fonts

    prettyprint "[font] Installing Source Code Pro..."

    ./install.sh SourceCodePro

    prettyprint "[font] DONE"


    # theme
    prettyprint "[theme] Pulling gruvbox for GNOME terminal..."

    cd ~/Documents
    git clone https://github.com/metalelf0/gnome-terminal-colors.git
    cd gnome-terminal-colors

    prettyprint "[theme] Running interactive installer..."

    ./install.sh

    prettyprint "[theme] DONE. Please restart terminal and configure font."
fi
